server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        time_tick:
          destination: timeTick
          contentType: application/json
      binders:
        rabbitmq-dev:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.10.12
                username: vagrant
                password: vagrant
                virtual-host: DEV